name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf6147c9fff161e389f1b2acdee45b2496bcab985235d382a4092ff4e205ee5e"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
