name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cec34522448a806acf5da9602ba138912e930dafe4b4346b51320a0e413d70e"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
