name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c48b1feccbc241b736ad7939b1339adffbdf802bd86132bee6f2a8cef3faf809"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
