name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42b15c8e040354e3130b3b26ae3bc68ebb670428bcb56ab9718efc9da60e2290"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
