name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4454543cf960a91f6c0a86fd7a4a987cd91c45de111548897a86c52442390a5"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
