name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a4d2a3df867b8b3fbfbf87d33d3c409760399a8eb6d8e84bfc26eae5fa23dce"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
