name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "329e4420612629608954f38c74e87e147479d3ecf0a1ba5c642427bdf5126924"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
